### PR TITLE
allow to pass in different co (e.g. bluebird.coroutine or Q.async)

### PR DESCRIPTION
**Pull request by mvayngrib**
backwards compatible

### CODE REVIEW

**Comment by mciparelli** [comment]
Thanks. I'll write some documentation about it and merge soon. Couple tests using some of the libraries you mentioned won't hurt :grin:

**Comment by mciparelli** [comment]
If you can make current tests pass with other libraries (just the ones you suggested should be fine) I'll be happy to merge.

**Comment by mvayngrib** [comment]
@mciparelli I added the tests (see the last commit)...but sadly, it doesn't pass with bluebird and q, as those don't seem to support yielding thunks.

**Comment by mciparelli** [comment]
Released as 2.0.0

**Pull request closed without merging**
